# Basic
name:         patrykboch.com
description:  dull notes abt software
url:          "https://patrykboch.com"
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
author:       "patrykboch"
twitter:
  username:   "patboch"
permalink:          /:year/:month/:day/:title/
markdown:           kramdown
# Sass
sass:
  style:            :compressed
plugins:
  - jekyll-seo-tag
  - jekyll-feed
